### ISSUE TITLE
"null" is a valid JSON value.

### ISSUE THREAD

**Issue by bulatbulat48** [Nykakin/chompjs#11]
```Python
json.loads("null")
```

Looks like an error but this literal is a valid JSON representation of null.

```Python
chompjs.parse_js_object("null")
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

https://www.ietf.org/rfc/rfc4627.txt?number=4627

**Comment by Nykakin** [comment]
@bulatbulat48, this is a bit difficult to implement right now, I'd like to make a refactoring to the code and then I think I'll be able to include this.

**Comment by Nykakin** [comment]
After re-examining this issue: this library search for first `[` or `{` to start parsing, which allows following code to work:
```python
>>> import chompjs
>>> 
>>> chompjs.parse_js_object('var some_interlan_json = {"a": 12}')
{'a': 12}
```
So I can't really parse single literals if I want to preserve this behaviour. At the very least data needs to be enclosed in array or a dict.
