### ISSUE TITLE
wrong result if "}" included

### ISSUE THREAD

**Issue by Akida31** [Nykakin/chompjs#16]
I want to parse the following js object:
```js
{hello: function() {console.log('hi');}}
```

For that I use chompjs like that
```py
from chompjs import parse_js_object
parse_js_object("{hello: function() {console.log('hi');}}")
```

The result:
```js
{'hello': "function() {console.log('hi');"}
```

but it should be:
```js
{'hello': "function() {console.log('hi');}"}
```

Could it be that the parser stops at the first closing curly bracket?

**Comment by Nykakin** [comment]
For now `chompjs` doesn't work's well with functions. For example it will break if a function has arguments:
```python
>>> chompjs.parse_js_object("{test: function(a, b, c){} }")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mariusz/Documents/Praca/venv/lib/python3.8/site-packages/chompjs/chompjs.py", line 29, in parse_js_object
    raise ValueError("Parser error: ... {}".format(str(exception).encode('utf-8')))
ValueError: Parser error: ... b' c){} }'
```
I have an update in mind that should solve both this and reported problem.

**Comment by Akida31** [comment]
I found a solution in which I doubled all quotes and passed all JavaScript Functions/ Specials as a String to python, because i did not need to change them. My implementation is like [this](https://gist.github.com/Akida31/bb99565a645f632d4c961f451ba384bc). It is a messy workaround but works

**Comment by Nykakin** [comment]
Since version 1.1.1 `chompjs` can handle JavaScript functions:
```python
>>> import chompjs
>>> chompjs.parse_js_object("{hello: function() {console.log('hi');}}")
{'hello': "function() {console.log('hi');}"}
>>> chompjs.parse_js_object("{test: function(a, b, c){} }")
{'test': 'function(a, b, c){} '}
```
