### ISSUE TITLE
Add parse_js_objects function.

### ISSUE THREAD

**Issue by Nykakin** [Nykakin/chompjs#43]
Currently the library extracts only the first JSON-like thing it encounters in the input string:
```python
>>> import chompjs
>>> data = """
... {'abc': 'test', 'foo': 12}
... 
... // some JS code
... 
... {'ghi': 'test', 'bar': 13}
... """)
>>> chompjs.parse_js_object(data)
{'abc': 'test', 'foo': 12}
```
Add a second method, `parse_js_objects` returning an iterator yielding all objects that were found and successfully parsed. Expected behavior:
```python
>>> import chompjs
>>> data = """
... {'abc': 'test', 'foo': 12}
... 
... // some JS code
... 
... {'ghi': 'test', 'bar': 13}
... """)
>>> for result in chompjs.parse_js_objects(data):
...     print(result)
... 
{'abc': 'test', 'foo': 12}
{'ghi': 'test', 'bar': 13}
```

**Comment by Roman-Kasianenko** [comment]
@Nykakin ,  could you please consider the possibility to keep/have in the result JSON then name of JS dict?

for example if we have js like this:

```
const testField1 = {
  name: 'name1',
  value: 'value1',
}

const testField2 = {
  name2: 'name2',
  value2: 'value2',
}
```

in a result we should have:

```
[{"testField1": {"name": "name1", "value": "value2"}}, {"testField2": {"name2": "name2", "value2": "value2"}}]
```

or this will be wrong or overcomplicated?

**Comment by Nykakin** [comment]
This would be wrong. JavaScript objects aren't always immediately assigned to a variable and don't always have a clear concept of a name. For example, they can be passed down as arguments to anonymous function:
```javascript
window.__NUXT__ = (function(a, b, c) {
    /*
   Some JavaScript code here
   */
})({"a": 123, "b": 232}, 11, [1, 2, 3, 4]));
```
