### ISSUE TITLE
Handling booleans expressed as !0 and !1

### ISSUE THREAD

**Issue by DiegoBaldassarMilleuno** [Nykakin/chompjs#55]
It is fairly common for JavaScript minifiers to represent literal `false` and `true` as `!1` and `!0` respectively.
Currently chompjs parses such expressions as strings:
```python
import chompjs
print(chompjs.parse_js_object('{a: !0}'))
```
Output:
```code
{'a': '!0'}
```
It would be a nice improvement if these expressions would be parsed as booleans. A more general solution handling the ! operator would be even better, although I assume simply handling these two cases would cover the vast majority of use cases.

**Comment by Nykakin** [comment]
For a quick solution you can pass customized JSONEncoder:
```python
from json import scanner, JSONDecoder
from json.decoder import scanstring

import chompjs


def custom_scanstring(*args, **kwargs):
    (s, end) = scanstring(*args, **kwargs)
    if s == "!0":
        return (True, end)
    elif s == "!1":
        return (False, end)
    else:
        return (s, end)


class CustomJsonDecoder(JSONDecoder):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.parse_string = custom_scanstring
        self.scan_once = scanner.py_make_scanner(self)
        

result = chompjs.parse_js_object(
    "{'a': !0, 'b': !1}",
    json_params={'cls': CustomJsonDecoder}
)
print(result)
```
Unfortunately I don't think it would be easy to implement directly in the library but I'll make some experiments when I'll manage to find some time.

**Comment by Nykakin** [comment]
Closing as inactive. Provided solution with customized `JSONDecoder` should suffice for now.
