### ISSUE TITLE
Segfault when passing empty string

### ISSUE THREAD

**Issue by abebus** [Nykakin/chompjs#61]
```
_chompjs.parse('')
Segmentation fault
```
Python 3.12.3 (main, Apr 27 2024, 19:00:21) [GCC 11.4.0] on linux
Platform Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

**Comment by Nykakin** [comment]
Fixed in #62 but generally speaking you should avoid using `_chompjs` package directly and rely on higher level functions from main `chompjs` module.

**Comment by abebus** [comment]
Thanks! 
But I prefer using `orjson` module, instead of builtin `json`, it would be nice to have an option to pass a custom `dumps` function to `parse_js_object`

**Comment by Nykakin** [comment]
Sounds like a good idea to allow customized loader.

Opened my own PR: https://github.com/Nykakin/chompjs/pull/63 because I also needed to update the documentation for this. Feel free to test it.
