### ISSUE TITLE
Fails with keys that start with _ or $

### ISSUE THREAD

**Issue by ArturGaspar** [Nykakin/chompjs#8]
chompjs.parse_js_object() fails with keys that start with _ or $, which are valid Javascript.

    >>> chompjs.parse_js_object("{a:123}")
    {'a': 123}
    >>> chompjs.parse_js_object("{_a:123}")
    Traceback (most recent call last):
      ...
    ValueError: Parser error: ... b'a:123}'
    >>> chompjs.parse_js_object("{$a:123}")
    Traceback (most recent call last):
      ...
    ValueError: Parser error: ... b'a:123}'

**Comment by Nykakin** [comment]
Hello @ArturGaspar this should be fixed in 1.0.15.
